backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Posts" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "frontmatter"
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Id", name: "id", widget: "hidden", default: "{{slug}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: "HH:mm", picker_utc: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "menu-category" # Used in routes, e.g., /admin/collections/blog
    label: "Menu Categories" # Used in the UI
    files:
      - label: "General menu" # Used in the UI
        name: "general-menu" # Used in routes, e.g., /admin/collections/blog
        editor:
          preview: false
        file: "src/menu-categories/general-menu.json" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        format: "json"
        fields: # The fields for each document, usually in front matter
          - {label: "Filterable", name: "filterable", widget: "hidden", default: false}
          - {label: "Description", name: "description", widget: "text"}
      - label: "Breakfast Boxes" # Used in the UI
        name: "breakfast-boxes" # Used in routes, e.g., /admin/collections/blog
        editor:
          preview: false
        file: "src/menu-categories/breakfast-boxes.json" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        format: "json"
        fields: # The fields for each document, usually in front matter
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Description", name: "description", widget: "text"}
      - label: "Sandwich Box Lunches" # Used in the UI
        name: "sandwich-box-lunches" # Used in routes, e.g., /admin/collections/blog
        editor:
          preview: false
        file: "src/menu-categories/sandwich-box-lunches.json" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        format: "json"
        fields: # The fields for each document, usually in front matter
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Description", name: "description", widget: "text"}
      - label: "Box Meals" # Used in the UI
        name: "box-meals" # Used in routes, e.g., /admin/collections/blog
        editor:
          preview: false
        file: "src/menu-categories/box-meals.json" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        format: "json"
        fields: # The fields for each document, usually in front matter
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Description", name: "description", widget: "text"}
      - label: "Salad Box Lunches" # Used in the UI
        name: "salad-box-lunches" # Used in routes, e.g., /admin/collections/blog
        editor:
          preview: false
        file: "src/menu-categories/salad-box-lunches.json" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        format: "json"
        fields: # The fields for each document, usually in front matter
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Description", name: "description", widget: "text"}
      - label: "BBQ Box Meals" # Used in the UI
        name: "bbq-box-meals" # Used in routes, e.g., /admin/collections/blog
        editor:
          preview: false
        file: "src/menu-categories/bbq-box-meals.json" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        format: "json"
        fields: # The fields for each document, usually in front matter
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Description", name: "description", widget: "text"}

  - name: "Menu" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Menu meal" # Used in the UI
    folder: "src/menu" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Id", name: "id", widget: "hidden", default: "{{slug}}"}
      - {label: "title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: "HH:mm", picker_utc: true}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - label: "Menu type"
        name: "type"
        widget: "select"
        options:
          - { label: "Breakfast Boxes", value: "breakfast-boxes" }
          - { label: "Sandwich Box Lunches", value: "sandwich-box-lunches" }
          - { label: "Box Meals", value: "box-meals" }
          - { label: "Salad Box Lunches", value: "salad-box-lunches" }
          - { label: "BBQ Box Meals", value: "bbq-box-meals" }

      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
